### ISSUE TITLE
Can't pause animation

### ISSUE THREAD

**Issue by dr808** [BenAHammond/vue-anime#16]
I can't figure out how to pause the animation. Any pointers? 

Thanks for your help and thanks for the plugin!

**Comment by mediv0** [comment]
you can do something like this:

```javascript
let animation = this.$anime({
    // animations
});
animation.pause();
```

more details here: https://animejs.com/documentation/#playPause

**Comment by dr808** [comment]
I probably should have put more details in my question. It's centered around where to place the `animation.pause()`. For example this obviously won't work:
```
methods: {
  animationMethod() {
    let animation = this.$anime({
    // animations
    });
  pauseAnimationMethod() {
    this.animationMethod.pause();
    };
```
I can't figure out how to pause the animation when called as a method. My use case involves the animation starts after being called by intersection observer, then I'd like to stop when off screen.

**Comment by mediv0** [comment]
You can try something like this:
```javascript
data() {
  return {
    animation: null
  }
}

methods: {
  animationMethod() {
   this.animation = this.$anime({
    // animations
   }),
  pauseAnimationMethod() {
    this.animation.pause();
  }
}

```
if you Want to do something like calling a method and not creating a new variable in data, there is a way but it's a little bit tricky.

check this: 

```javascript
let methods= {
    animationMethod() {
        if (anime.running.length === 0) {
            return anime({
                // animations
            });
        } 
        else {
            return anime.running[0];
        }
    },
    pauseAnimationMethod() {
        this.animationMethod().pause();
    }
}
```

when you trying to call animationMethod function in pauseAnimationMethod (like something you did), anime.js will create a new instance from that function.
so your start animation will run on another instance and your pause in another too. they are not linked! that's why you can't pause your animation.

you can fix this by getting all active anime.js instances currently running. and return what you want
```javascript
anime.running  // will return an array of active instances
```

in the code above I am checking if there are not any active instances, -> create one
otherwise, return the active instance ( in this case we only have one instance, and it's in index 0).

**Comment by dr808** [comment]
That works! I recognized having multiple instances as the problem, but I never could figure out how to fix it. Thanks bro!

**Comment by Pk13055** [comment]
Can you close the issue if it's resolved?
